services:
  ama-db:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ama-db:/var/lib/postgresql/data

volumes:
  ama-db:
    driver: local