services:
  ama-db:
    container_name: ama-db
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - ../.prod.env
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ama-db-prod:/var/lib/postgresql/data
    networks:
      - ama-shared-network
  ama-valkey:
    image: valkey/valkey:7.2.6-alpine
    container_name: ama-valkey
    command: valkey-server --save 60 1 --loglevel verbose
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ama-valkey-prod:/data
    networks:
      - ama-shared-network
  ama-go:
    container_name: ama-go
    image: ama-go
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./build/docker/Dockerfile
    volumes:
      - ../.prod.env:/app/.env
    env_file:
      - ../.prod.env
    ports:
      - ${PORT:-5001}:5001
    depends_on:
      - ama-db
      - ama-valkey
    networks:
      - ama-shared-network

networks:
  ama-shared-network:
    external: true

volumes:
  ama-db-prod:
    driver: local
  ama-valkey-prod:
    driver: local