services:
  ama-go:
    image: ama-go-local
    command: air # Air entrypoint
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./build/docker/local.Dockerfile
    ports:
      - 5001:5001
    env_file:
      - ../.env
    depends_on:
      - ama-db
      - ama-valkey
    volumes:
      - ..:/app
      - /app/tmp # Air needs a temporary directory
      - ../.env:/app/.env
  ama-db:
    container_name: ama-db
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ama-db:/var/lib/postgresql/data
  ama-valkey:
    image: valkey/valkey:7.2.6-alpine
    container_name: ama-valkey
    command: valkey-server --save 60 1 --loglevel verbose
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ama-valkey:/data

volumes:
  ama-db:
    driver: local
  ama-valkey:
    driver: local