services:
  ama-valkey-test:
    image: valkey/valkey:7.2.6-alpine
    container_name: ama-valkey-test
    restart: unless-stopped
    ports:
      - 6380:6379
  ama-db-test:
    image: postgres:alpine
    ports:
      - ${DB_PORT:-5433}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-testuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-testpassword}
      POSTGRES_DB: ${DB_NAME:-testdb}