// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID            uuid.UUID        `db:"id" json:"id"`
	RoomID        uuid.UUID        `db:"room_id" json:"room_id"`
	Message       string           `db:"message" json:"message"`
	ReactionCount int32            `db:"reaction_count" json:"reaction_count"`
	Answered      bool             `db:"answered" json:"answered"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Room struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	UserID      uuid.UUID        `db:"user_id" json:"user_id"`
	Description string           `db:"description" json:"description"`
}

type User struct {
	ID             uuid.UUID        `db:"id" json:"id"`
	Email          string           `db:"email" json:"email"`
	Name           string           `db:"name" json:"name"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	Photo          string           `db:"photo" json:"photo"`
	EnablePicture  bool             `db:"enable_picture" json:"enable_picture"`
	Provider       string           `db:"provider" json:"provider"`
	ProviderUserID string           `db:"provider_user_id" json:"provider_user_id"`
	NewUser        bool             `db:"new_user" json:"new_user"`
}
