// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	RoomID        uuid.UUID   `db:"room_id" json:"room_id"`
	Message       string      `db:"message" json:"message"`
	ReactionCount int32       `db:"reaction_count" json:"reaction_count"`
	Answered      bool        `db:"answered" json:"answered"`
	CreatedAt     pgtype.Date `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Date `db:"updated_at" json:"updated_at"`
}

type Room struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	Name      string      `db:"name" json:"name"`
	CreatedAt pgtype.Date `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Date `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID           uuid.UUID        `db:"id" json:"id"`
	Email        string           `db:"email" json:"email"`
	PasswordHash string           `db:"password_hash" json:"password_hash"`
	Name         string           `db:"name" json:"name"`
	Bio          string           `db:"bio" json:"bio"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
