// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID            uuid.UUID
	RoomID        uuid.UUID
	Message       string
	ReactionCount int32
	Answered      bool
	CreatedAt     pgtype.Date
	UpdatedAt     pgtype.Date
}

type Room struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Date
	UpdatedAt pgtype.Date
}
