// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, bio)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, bio, created_at
`

type CreateUserParams struct {
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	Name         string `db:"name" json:"name"`
	Bio          string `db:"bio" json:"bio"`
}

type CreateUserRow struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	Email     string           `db:"email" json:"email"`
	Name      string           `db:"name" json:"name"`
	Bio       string           `db:"bio" json:"bio"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Bio,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT
  "id", "room_id", "message", "reaction_count", "answered", "created_at"
FROM messages
WHERE id = $1
`

type GetMessageRow struct {
	ID            uuid.UUID        `db:"id" json:"id"`
	RoomID        uuid.UUID        `db:"room_id" json:"room_id"`
	Message       string           `db:"message" json:"message"`
	ReactionCount int32            `db:"reaction_count" json:"reaction_count"`
	Answered      bool             `db:"answered" json:"answered"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (GetMessageRow, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i GetMessageRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Message,
		&i.ReactionCount,
		&i.Answered,
		&i.CreatedAt,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT 
  "id", "name", "user_id"
FROM rooms
WHERE id = $1
`

type GetRoomRow struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Name   string    `db:"name" json:"name"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetRoom(ctx context.Context, id uuid.UUID) (GetRoomRow, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i GetRoomRow
	err := row.Scan(&i.ID, &i.Name, &i.UserID)
	return i, err
}

const getRoomMessages = `-- name: GetRoomMessages :many
SELECT
  "id", "room_id", "message", "reaction_count", "answered", "created_at"
FROM messages
WHERE room_id = $1 ORDER BY created_at DESC
`

type GetRoomMessagesRow struct {
	ID            uuid.UUID        `db:"id" json:"id"`
	RoomID        uuid.UUID        `db:"room_id" json:"room_id"`
	Message       string           `db:"message" json:"message"`
	ReactionCount int32            `db:"reaction_count" json:"reaction_count"`
	Answered      bool             `db:"answered" json:"answered"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetRoomMessages(ctx context.Context, roomID uuid.UUID) ([]GetRoomMessagesRow, error) {
	rows, err := q.db.Query(ctx, getRoomMessages, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomMessagesRow
	for rows.Next() {
		var i GetRoomMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Message,
			&i.ReactionCount,
			&i.Answered,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRooms = `-- name: GetRooms :many
SELECT
  "id", "name", "user_id", "created_at"
FROM rooms ORDER BY created_at ASC
`

type GetRoomsRow struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	Name      string           `db:"name" json:"name"`
	UserID    uuid.UUID        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetRooms(ctx context.Context) ([]GetRoomsRow, error) {
	rows, err := q.db.Query(ctx, getRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomsRow
	for rows.Next() {
		var i GetRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, bio, password_hash, created_at
FROM users
WHERE email = $1 LIMIT 1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID        `db:"id" json:"id"`
	Email        string           `db:"email" json:"email"`
	Name         string           `db:"name" json:"name"`
	Bio          string           `db:"bio" json:"bio"`
	PasswordHash string           `db:"password_hash" json:"password_hash"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Bio,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages
  ("room_id", "message") VALUES
  ($1, $2)
RETURNING "id", "created_at"
`

type InsertMessageParams struct {
	RoomID  uuid.UUID `db:"room_id" json:"room_id"`
	Message string    `db:"message" json:"message"`
}

type InsertMessageRow struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (InsertMessageRow, error) {
	row := q.db.QueryRow(ctx, insertMessage, arg.RoomID, arg.Message)
	var i InsertMessageRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertRoom = `-- name: InsertRoom :one
INSERT INTO rooms
  ("name", "user_id") VALUES
  ($1, $2)
RETURNING "id", "created_at"
`

type InsertRoomParams struct {
	Name   string    `db:"name" json:"name"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type InsertRoomRow struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertRoom(ctx context.Context, arg InsertRoomParams) (InsertRoomRow, error) {
	row := q.db.QueryRow(ctx, insertRoom, arg.Name, arg.UserID)
	var i InsertRoomRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const markMessageAsAnswered = `-- name: MarkMessageAsAnswered :exec
UPDATE messages
SET
  answered = true,
  updated_at = now()
WHERE
  id = $1
`

func (q *Queries) MarkMessageAsAnswered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMessageAsAnswered, id)
	return err
}

const reactToMessage = `-- name: ReactToMessage :one
UPDATE messages
SET
  reaction_count = reaction_count + 1
WHERE
  id = $1
RETURNING reaction_count
`

func (q *Queries) ReactToMessage(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, reactToMessage, id)
	var reaction_count int32
	err := row.Scan(&reaction_count)
	return reaction_count, err
}

const removeReactionFromMessage = `-- name: RemoveReactionFromMessage :one
UPDATE messages
SET
  reaction_count = reaction_count - 1
WHERE
  id = $1 AND reaction_count > 0
RETURNING reaction_count
`

func (q *Queries) RemoveReactionFromMessage(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, removeReactionFromMessage, id)
	var reaction_count int32
	err := row.Scan(&reaction_count)
	return reaction_count, err
}
